
import "./App.css";
import { useState } from "react";
import { jsPDF } from "jspdf";
import Loading from "./components/Loading";
import { analyzeResume } from "./services/resumeAnalysisService";
import Hero from "./components/Hero";
import Result from "./components/Result";
import Footer from "./components/Footer";
import AnalyzeButton from "./components/AnalyzeButton";
import JobDescription from "./components/JobDescription";
import ResumeUpload from "./components/ResumeUpload";

function App() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [jobDescription, setJobDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [analysis, setAnalysis] = useState(null);
  const [error, setError] = useState("");

  const handleAnalyze = async () => {
    setLoading(true);
    setError("");
    setShowResult(false);

    try {
      const data = await analyzeResume(selectedFile, jobDescription);
      setAnalysis(data);
      setShowResult(true);
    } catch (err) {
      console.error(err);
      setError("Analysis failed. Please try again with a valid PDF and job description.");
    } finally {
      setLoading(false);
    }
  };

  const handleStartOver = () => {
    setShowResult(false);
    setAnalysis(null);
    setError("");
  };

  const handleDownloadReport = () => {
    if (!analysis) {
      return;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFillColor(7, 17, 31);
    doc.rect(0, 0, pageWidth, 40, "F");
    doc.setTextColor(248, 250, 252);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("Resume Analyzer AI Report", 14, 20);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text("Professional resume intelligence summary", 14, 30);

    let y = 50;
    const addSection = (title, items) => {
      if (!items || items.length === 0) {
        return y;
      }

      doc.setTextColor(15, 23, 42);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.text(title, 14, y);
      y += 7;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);
      items.forEach((item) => {
        const lines = doc.splitTextToSize(`• ${item}`, 180);
        doc.text(lines, 18, y);
        y += lines.length * 5.5;

        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      });

      y += 4;
      return y;
    };

    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Score Summary", 14, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`ATS Score: ${analysis.ats_score || "N/A"}/100`, 18, y);
    y += 6;
    doc.text(`Resume Score: ${analysis.resume_score || "N/A"}/100`, 18, y);
    y += 6;
    doc.text(`Overall Rating: ${analysis.overall_rating || "N/A"}/100`, 18, y);
    y += 6;
    doc.text(`Job Match: ${analysis.job_match_percentage || "N/A"}%`, 18, y);
    y += 12;

    y = addSection("Strengths", analysis.strengths || []);
    y = addSection("Weaknesses", analysis.weaknesses || []);
    y = addSection("Missing Keywords", analysis.missing_keywords || []);
    y = addSection("Recommended Skills", analysis.recommended_skills || []);
    y = addSection("Roadmap to Close Gaps", analysis.recommended_learning_path || []);
    y = addSection("AI Recommendations", analysis.ai_suggestions?.professional_recommendations || []);

    doc.save("resume-analysis-report.pdf");
  };

  if (loading) {
    return <Loading setLoading={setLoading} setShowResults={setShowResult} />;
  }

  if (showResult) {
    return (
      <>
        <section className="results-page">
          <div className="results-page-header">
            <h1>Resume Analysis Ready</h1>
            <p>Your review is generated by the backend AI analysis service using the configured API credentials.</p>
          </div>
          <Result analysis={analysis} />
          <div className="results-actions">
            <button className="secondary-btn" onClick={handleStartOver}>
              Analyze Another Resume
            </button>
            <button className="primary-btn" onClick={handleDownloadReport}>
              Download Report
            </button>
          </div>
        </section>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Hero />
      <ResumeUpload selectedFile={selectedFile} setSelectedFile={setSelectedFile} />
      <JobDescription jobDescription={jobDescription} setJobDescription={setJobDescription} />
      <AnalyzeButton selectedFile={selectedFile} jobDescription={jobDescription} onAnalyze={handleAnalyze} />
      {error && <p className="error-message">{error}</p>}
      <Footer />
    </>
  );
}

export default App;